### ISSUE TITLE
Docker instructions to combined install

### ISSUE THREAD

**Issue by benhaynes** [directus/docs#38]
We need to include an _Install with Docker_ section to the combined install Docs.

**Comment by hartwm** [comment]
Do we have a timeframe for this? 
`docker-compose build` 
`docker-compose up`
`localhost:8080/admin`

Plug in DB info "root" as password
"Trouble processing request. Try again after refreshing the page."

<img width="847" alt="screen shot 2018-10-29 at 5 03 21 pm" src="https://user-images.githubusercontent.com/2334164/47680232-a423f080-db9c-11e8-839f-8895f1de55fc.png">

**Comment by benhaynes** [comment]
There are some initial conversations happening over here (and within our Slack community): https://github.com/directus/docker/issues

Once we have the architectural aspects nailed down we should have a container pretty quickly.

**Comment by BlackDark** [comment]
Hi guys, how's the state in providing a fully working setup via docker?
Any chance i can help you with the setup?

It would be nice if i can startup the necessary services with one compose so i can test the v7 in our project.

**Comment by benhaynes** [comment]
Thanks @BlackDark!

It's going well. We are tracking all Docker related stuff over here: https://github.com/directus/docker

As of now, @WoLfulus is working on getting the README and combined build up and running... so I'll let him speak to how far along things are and if he needs any help.

**Comment by WoLfulus** [comment]
Docker support is still experimental and I'm still testing the api container with nginx and fpm setup (it was apache).

@BlackDark As @benhaynes said, I'm working on the README this week... I'll try to provide a compose file asap.

**Comment by BlackDark** [comment]
Hey @WoLfulus i tried your single-api scripts in the docker repo.
Locally on my macbook it works and i can login but the deployed instance on a VM it does not work. I can access the login page but as soon as i enter the correct login fields loading starts and fails with bad gateway. Do you have any ideas?

In the yml i changed the port mappings and updated the API-endpoint url.

**Comment by WoLfulus** [comment]
Can you share the docker-compose contents and the VM specs you're running? like distro, docker version, docker-compose version?

**Comment by BlackDark** [comment]
compose file:

```yaml
version: "3"

services:

  #
  # Database
  #
  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "somedb"
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_USER: "someusername"
      MYSQL_PASSWORD: "somepassword"
    # That is not needed i think. Internal container connection possible without exposing host ports.
    # At least works on macos without exposing.
    #ports:
    #  - 3306:3306

  #
  # API
  #
  api:
    image: directus/api:latest
    environment:
      DATABASE_HOST: "database"
      DATABASE_NAME: "somedb"
      DATABASE_USERNAME: "someusername"
      DATABASE_PASSWORD: "somepassword"
      ADMIN_EMAIL: "admin@localhost.com"
      ADMIN_PASSWORD: "directusrocks"
    ports:
      - 30030:80
    depends_on:
    - database

  #
  # Dashboard
  #
  app:
    image: directus/app:latest
    environment:
      API_ENDPOINT: "API; http://internal-address:30030/_/"
      # Tried with remapping
      #API_ENDPOINT: "API; https://internal-address/dir7/api/_/"
    ports:
      - 30031:80
    depends_on:
    - api
```

VM specs:
OS: SLES12 SP3
Docker: 17.03.2-ce
Docker-compose: 1.21.2
